#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := thermal_sampler_gateway
#IDF_PATH := /opt/esp32/esp-idf/
include $(IDF_PATH)/make/project.mk

